import type { Metadata } from "next";
import "./globals.css";
import "../styles/index.css"

export const metadata: Metadata = {
  title: "Emin Travel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-50">
        {children}
      </body>
    </html>
  );
}
